import type { Notification } from '@/lib/types/notifications';

export const mockNotifications: Notification[] = [
  {
    _id: '1',
    user_id: 'user_1',
    title: 'New Instagram Message',
    message: 'New message: "Hey, what\'s the price for..."',
    type: 'social',
    status: 'unread',
    priority: 'high',
    tags: [],
    metadata: {
      conversationId: 'conv_123',
      senderId: '1148492026747408',
      platform: 'instagram',
    },
    dismissible: true,
    click_count: 0,
    is_broadcast: false,
    target_channels: ['in-app'],
    created_at: new Date(Date.now() - 2 * 60 * 1000).toISOString(), // 2m ago
    updated_at: new Date(Date.now() - 2 * 60 * 1000).toISOString(),
  },
  {
    _id: '2',
    user_id: 'user_1',
    title: 'Automation Triggered',
    message: '"Welcome New Commenters" replied to @sarah_designs',
    type: 'automation',
    status: 'read',
    priority: 'medium',
    tags: ['automation'],
    metadata: {
      automationId: 'auto_123',
      automationName: 'Welcome New Commenters',
    },
    dismissible: true,
    click_count: 1,
    is_broadcast: false,
    target_channels: ['in-app'],
    created_at: new Date(Date.now() - 15 * 60 * 1000).toISOString(), // 15m ago
    updated_at: new Date(Date.now() - 10 * 60 * 1000).toISOString(),
  },
  {
    _id: '3',
    user_id: 'user_1',
    title: 'Credits Running Low',
    message: 'You have 45 credits remaining (~22 replies)',
    type: 'usage',
    status: 'unread',
    priority: 'high',
    action_url: '/dashboard/credits',
    action_label: 'Top up credits',
    tags: ['credits'],
    dismissible: true,
    click_count: 0,
    is_broadcast: false,
    target_channels: ['in-app'],
    created_at: new Date(Date.now() - 1 * 60 * 60 * 1000).toISOString(), // 1h ago
    updated_at: new Date(Date.now() - 1 * 60 * 60 * 1000).toISOString(),
  },
  {
    _id: '4',
    user_id: 'user_1',
    title: 'Payment Successful',
    message: 'Pro Pack (2000 credits) - ₹1,499',
    type: 'billing',
    status: 'read',
    priority: 'low',
    action_url: '/dashboard/credits',
    action_label: 'View invoice',
    tags: ['payment'],
    dismissible: true,
    click_count: 2,
    is_broadcast: false,
    target_channels: ['in-app'],
    created_at: new Date(Date.now() - 24 * 60 * 60 * 1000).toISOString(), // 1d ago
    updated_at: new Date(Date.now() - 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    _id: '5',
    user_id: 'user_1',
    title: 'New Feature: AI Tone Selection',
    message:
      'Customize how your AI replies sound - Professional, Friendly, or Casual',
    type: 'new_feature',
    status: 'unread',
    priority: 'medium',
    action_url: '/dashboard/automations',
    action_label: 'Try it now',
    tags: ['feature'],
    dismissible: true,
    click_count: 0,
    is_broadcast: true,
    target_channels: ['in-app'],
    created_at: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(), // 2d ago
    updated_at: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    _id: '6',
    user_id: 'user_1',
    title: 'Weekly Performance Report',
    message: 'Your automations handled 347 comments this week (+23%)',
    type: 'performance',
    status: 'read',
    priority: 'low',
    tags: ['report'],
    dismissible: true,
    click_count: 1,
    is_broadcast: false,
    target_channels: ['in-app'],
    created_at: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(), // 3d ago
    updated_at: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    _id: '7',
    user_id: 'user_1',
    title: 'Security Alert',
    message: 'New login detected from Mumbai, India',
    type: 'security',
    status: 'read',
    priority: 'urgent',
    action_url: '/dashboard/settings/security',
    action_label: 'Review activity',
    tags: ['security'],
    dismissible: true,
    click_count: 1,
    is_broadcast: false,
    target_channels: ['in-app'],
    created_at: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(), // 5d ago
    updated_at: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    _id: '8',
    user_id: 'user_1',
    title: 'Scheduled Maintenance',
    message: 'Brief downtime expected on Jan 20, 2:00 AM IST',
    type: 'maintenance',
    status: 'read',
    priority: 'medium',
    tags: ['maintenance'],
    dismissible: true,
    click_count: 0,
    is_broadcast: true,
    target_channels: ['in-app'],
    created_at: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(), // 7d ago
    updated_at: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
  },
];
